module Constant.Mailer where

_MAIL_REGISTRATION_REGISTRATION_CONFIRMATION :: String
_MAIL_REGISTRATION_REGISTRATION_CONFIRMATION = "registrationConfirmation"

_MAIL_REGISTRATION_CREATED_ANALYTICS :: String
_MAIL_REGISTRATION_CREATED_ANALYTICS = "registrationCreatedAnalytics"

_MAIL_RESET_PASSWORD :: String
_MAIL_RESET_PASSWORD = "resetPassword"

_MAIL_TEMPLATE_ROOT :: String
_MAIL_TEMPLATE_ROOT = "templates/mail/"

_MAIL_TEMPLATE_ATTACHMENTS_FOLDER :: String
_MAIL_TEMPLATE_ATTACHMENTS_FOLDER = "attachments"

_MAIL_TEMPLATE_COMMON_FOLDER :: String
_MAIL_TEMPLATE_COMMON_FOLDER = "_common"

_MAIL_TEMPLATE_PLAIN_NAME :: String
_MAIL_TEMPLATE_PLAIN_NAME = "message.txt.j2"

_MAIL_TEMPLATE_HTML_NAME :: String
_MAIL_TEMPLATE_HTML_NAME = "message.html.j2"
