module Util.Alphabet where

convertToLetter :: Int -> Char
convertToLetter 1 = 'a'
convertToLetter 2 = 'b'
convertToLetter 3 = 'c'
convertToLetter 4 = 'd'
convertToLetter 5 = 'e'
convertToLetter 6 = 'f'
convertToLetter 7 = 'g'
convertToLetter 8 = 'h'
convertToLetter 9 = 'i'
convertToLetter 10 = 'j'
convertToLetter 11 = 'k'
convertToLetter 12 = 'l'
convertToLetter 13 = 'm'
convertToLetter 14 = 'n'
convertToLetter 15 = 'o'
convertToLetter 16 = 'p'
convertToLetter 17 = 'q'
convertToLetter 18 = 'r'
convertToLetter 19 = 's'
convertToLetter 20 = 't'
convertToLetter 21 = 'u'
convertToLetter 22 = 'v'
convertToLetter 23 = 'w'
convertToLetter 24 = 'x'
convertToLetter 25 = 'y'
convertToLetter 26 = 'z'
convertToLetter _ = '-'
