module Wizard.Api.Handler.Swagger.Api where

import Data.Swagger
import Servant
import Servant.Swagger
import Servant.Swagger.UI

import RegistryLib.Api.Resource.Organization.OrganizationSM ()
import RegistryLib.Api.Resource.Organization.OrganizationSimpleSM ()
import Shared.Common.Api.Resource.Common.AesonSM ()
import Shared.Common.Api.Resource.Common.EntityCreatedWithIdSM ()
import Shared.Common.Api.Resource.Common.FileSM ()
import Shared.Common.Api.Resource.Common.PageMetadataSM ()
import Shared.Common.Api.Resource.Dev.DevExecutionResultSM ()
import Shared.Common.Api.Resource.Dev.DevExecutionSM ()
import Shared.Common.Api.Resource.Dev.DevSectionSM ()
import Shared.Common.Api.Resource.Info.InfoSM ()
import Shared.Component.Api.Resource.Component.ComponentSM ()
import Shared.Coordinate.Api.Resource.Coordinate.CoordinateSM ()
import Shared.DocumentTemplate.Api.Resource.DocumentTemplate.DocumentTemplateSM ()
import Shared.DocumentTemplate.Api.Resource.DocumentTemplateBundle.DocumentTemplateBundleSM ()
import Shared.KnowledgeModel.Api.Resource.KnowledgeModel.KnowledgeModelChangeSM ()
import Shared.KnowledgeModel.Api.Resource.KnowledgeModel.Package.KnowledgeModelPackagePhaseSM ()
import Shared.Locale.Api.Resource.Locale.LocaleSimpleSM ()
import Shared.Locale.Api.Resource.Locale.LocaleSuggestionSM ()
import Shared.PersistentCommand.Api.Resource.PersistentCommand.PersistentCommandChangeSM ()
import Shared.PersistentCommand.Api.Resource.PersistentCommand.PersistentCommandSM ()
import Shared.Prefab.Api.Resource.Prefab.PrefabSM ()
import Wizard.Api.Handler.Api
import Wizard.Api.Resource.ActionKey.ActionKeyTypeSM ()
import Wizard.Api.Resource.Auth.AuthConsentSM ()
import Wizard.Api.Resource.Common.PageSM ()
import Wizard.Api.Resource.Config.ClientConfigSM ()
import Wizard.Api.Resource.Document.DocumentCreateSM ()
import Wizard.Api.Resource.Document.DocumentSM ()
import Wizard.Api.Resource.DocumentTemplate.Asset.DocumentTemplateAssetChangeSM ()
import Wizard.Api.Resource.DocumentTemplate.Asset.DocumentTemplateAssetCreateSM ()
import Wizard.Api.Resource.DocumentTemplate.Asset.DocumentTemplateAssetSM ()
import Wizard.Api.Resource.DocumentTemplate.DocumentTemplateChangeSM ()
import Wizard.Api.Resource.DocumentTemplate.DocumentTemplateDetailSM ()
import Wizard.Api.Resource.DocumentTemplate.DocumentTemplatePhaseSM ()
import Wizard.Api.Resource.DocumentTemplate.DocumentTemplateSimpleSM ()
import Wizard.Api.Resource.DocumentTemplate.Draft.DocumentTemplateDraftChangeSM ()
import Wizard.Api.Resource.DocumentTemplate.Draft.DocumentTemplateDraftCreateSM ()
import Wizard.Api.Resource.DocumentTemplate.Draft.DocumentTemplateDraftDataChangeSM ()
import Wizard.Api.Resource.DocumentTemplate.Draft.DocumentTemplateDraftDataSM ()
import Wizard.Api.Resource.DocumentTemplate.Draft.DocumentTemplateDraftDetailSM ()
import Wizard.Api.Resource.DocumentTemplate.Draft.DocumentTemplateDraftListSM ()
import Wizard.Api.Resource.DocumentTemplate.File.DocumentTemplateFileChangeSM ()
import Wizard.Api.Resource.DocumentTemplate.File.DocumentTemplateFileListSM ()
import Wizard.Api.Resource.DocumentTemplate.Folder.DocumentTemplateFolderDeleteSM ()
import Wizard.Api.Resource.DocumentTemplate.Folder.DocumentTemplateFolderMoveSM ()
import Wizard.Api.Resource.Feedback.FeedbackCreateSM ()
import Wizard.Api.Resource.Feedback.FeedbackSM ()
import Wizard.Api.Resource.File.FileCreateSM ()
import Wizard.Api.Resource.KnowledgeModel.Bundle.KnowledgeModelBundleFileSM ()
import Wizard.Api.Resource.KnowledgeModel.Editor.KnowledgeModelEditorChangeSM ()
import Wizard.Api.Resource.KnowledgeModel.Editor.KnowledgeModelEditorCreateSM ()
import Wizard.Api.Resource.KnowledgeModel.Editor.KnowledgeModelEditorDetailSM ()
import Wizard.Api.Resource.KnowledgeModel.Editor.KnowledgeModelEditorStateSM ()
import Wizard.Api.Resource.KnowledgeModel.Migration.KnowledgeModelMigrationCreateSM ()
import Wizard.Api.Resource.KnowledgeModel.Migration.KnowledgeModelMigrationResolutionSM ()
import Wizard.Api.Resource.KnowledgeModel.Migration.KnowledgeModelMigrationSM ()
import Wizard.Api.Resource.KnowledgeModel.Migration.KnowledgeModelMigrationStateSM ()
import Wizard.Api.Resource.KnowledgeModel.Package.KnowledgeModelPackageChangeSM ()
import Wizard.Api.Resource.KnowledgeModel.Package.KnowledgeModelPackageDetailSM ()
import Wizard.Api.Resource.KnowledgeModel.Package.KnowledgeModelPackageSuggestionSM ()
import Wizard.Api.Resource.KnowledgeModel.Package.Publish.KnowledgeModelPackagePublishEditorSM ()
import Wizard.Api.Resource.KnowledgeModel.Package.Publish.KnowledgeModelPackagePublishMigrationSM ()
import Wizard.Api.Resource.KnowledgeModel.Secret.KnowledgeModelSecretChangeSM ()
import Wizard.Api.Resource.KnowledgeModel.Secret.KnowledgeModelSecretSM ()
import Wizard.Api.Resource.Locale.LocaleChangeSM ()
import Wizard.Api.Resource.Locale.LocaleCreateSM ()
import Wizard.Api.Resource.Locale.LocaleDetailSM ()
import Wizard.Api.Resource.Locale.LocaleSM ()
import Wizard.Api.Resource.PersistentCommand.PersistentCommandDetailSM ()
import Wizard.Api.Resource.PersistentCommand.PersistentCommandSM ()
import Wizard.Api.Resource.Project.Action.ProjectActionChangeSM ()
import Wizard.Api.Resource.Project.Action.ProjectActionSM ()
import Wizard.Api.Resource.Project.Comment.ProjectCommentThreadAssignedSM ()
import Wizard.Api.Resource.Project.Detail.ProjectDetailPreviewSM ()
import Wizard.Api.Resource.Project.Detail.ProjectDetailQuestionnaireSM ()
import Wizard.Api.Resource.Project.Detail.ProjectDetailReportSM ()
import Wizard.Api.Resource.Project.Detail.ProjectDetailSM ()
import Wizard.Api.Resource.Project.Detail.ProjectDetailSettingsSM ()
import Wizard.Api.Resource.Project.Detail.ProjectDetailWsSM ()
import Wizard.Api.Resource.Project.Event.ProjectEventListSM ()
import Wizard.Api.Resource.Project.Importer.ProjectImporterChangeSM ()
import Wizard.Api.Resource.Project.Importer.ProjectImporterSM ()
import Wizard.Api.Resource.Project.Migration.ProjectMigrationChangeSM ()
import Wizard.Api.Resource.Project.Migration.ProjectMigrationCreateSM ()
import Wizard.Api.Resource.Project.Migration.ProjectMigrationSM ()
import Wizard.Api.Resource.Project.ProjectContentChangeSM ()
import Wizard.Api.Resource.Project.ProjectContentSM ()
import Wizard.Api.Resource.Project.ProjectCreateFromTemplateSM ()
import Wizard.Api.Resource.Project.ProjectCreateSM ()
import Wizard.Api.Resource.Project.ProjectReportSM ()
import Wizard.Api.Resource.Project.ProjectSM ()
import Wizard.Api.Resource.Project.ProjectSettingsChangeSM ()
import Wizard.Api.Resource.Project.ProjectShareChangeSM ()
import Wizard.Api.Resource.Project.ProjectSimpleSM ()
import Wizard.Api.Resource.Project.ProjectSuggestionSM ()
import Wizard.Api.Resource.Project.Version.ProjectVersionChangeSM ()
import Wizard.Api.Resource.Project.Version.ProjectVersionRevertSM ()
import Wizard.Api.Resource.Registry.RegistryConfirmationSM ()
import Wizard.Api.Resource.Registry.RegistryCreateSM ()
import Wizard.Api.Resource.Registry.RegistryOrganizationSM ()
import Wizard.Api.Resource.Report.ReportSM ()
import Wizard.Api.Resource.Submission.SubmissionCreateSM ()
import Wizard.Api.Resource.Submission.SubmissionSM ()
import Wizard.Api.Resource.Tenant.Config.TenantConfigChangeSM ()
import Wizard.Api.Resource.Tenant.Config.TenantConfigSM ()
import Wizard.Api.Resource.Tenant.Config.TenantConfigSubmissionServiceSimpleSM ()
import Wizard.Api.Resource.Tenant.TenantChangeSM ()
import Wizard.Api.Resource.Tenant.TenantCreateSM ()
import Wizard.Api.Resource.Tenant.TenantDetailSM ()
import Wizard.Api.Resource.Tenant.TenantSM ()
import Wizard.Api.Resource.TypeHint.TypeHintISM ()
import Wizard.Api.Resource.TypeHint.TypeHintRequestSM ()
import Wizard.Api.Resource.TypeHint.TypeHintTestRequestSM ()
import Wizard.Api.Resource.User.UserChangeSM ()
import Wizard.Api.Resource.User.UserCreateSM ()
import Wizard.Api.Resource.User.UserPasswordSM ()
import Wizard.Api.Resource.User.UserProfileChangeSM ()
import Wizard.Api.Resource.User.UserProfileSM ()
import Wizard.Api.Resource.User.UserSM ()
import Wizard.Api.Resource.User.UserStateSM ()
import Wizard.Api.Resource.User.UserSubmissionPropListSM ()
import Wizard.Api.Resource.User.UserSubmissionPropSM ()
import Wizard.Api.Resource.UserToken.ApiKeyCreateSM ()
import Wizard.Api.Resource.UserToken.AppKeyCreateSM ()
import Wizard.Api.Resource.UserToken.UserTokenListSM ()
import Wizard.Api.Resource.Websocket.ProjectMessageSM ()
import Wizard.Api.Resource.Websocket.WebsocketSM ()
import WizardLib.Public.Api.Resource.PersistentCommand.PersistentCommandListSM ()
import WizardLib.Public.Api.Resource.TemporaryFile.TemporaryFileSM ()
import WizardLib.Public.Api.Resource.Tenant.Limit.TenantLimitBundleChangeSM ()
import WizardLib.Public.Api.Resource.Tenant.Usage.WizardUsageSM ()
import WizardLib.Public.Api.Resource.User.Group.UserGroupDetailSM ()
import WizardLib.Public.Api.Resource.User.UserLocaleSM ()
import WizardLib.Public.Api.Resource.UserToken.LoginSM ()
import WizardLib.Public.Api.Resource.UserToken.UserTokenSM ()

type SwaggerAPI = SwaggerSchemaUI "swagger-ui" "swagger.json"

swagger :: Swagger
swagger =
  let s = toSwagger applicationApi
   in s
        { _swaggerInfo =
            s._swaggerInfo
              { _infoTitle = "Wizard API"
              , _infoDescription = Just "API specification for Wizard"
              , _infoVersion = "4.26.2"
              , _infoLicense =
                  Just $
                    License
                      { _licenseName = "Apache-2.0"
                      , _licenseUrl = Just . URL $ "https://raw.githubusercontent.com/ds-wizard/engine-backend/main/LICENSE.md"
                      }
              }
        , _swaggerBasePath = Just "/wizard-api"
        }

swaggerServer :: Server SwaggerAPI
swaggerServer = swaggerSchemaUIServer swagger
