resolver: nightly-2022-11-16

packages:
- engine-registry
- engine-shared
- engine-wizard
- engine-wizard-metamodel-migrator

extra-deps:
  - vendor/postgresql-migration
  - vendor/servant-errors
  - vendor/servant-mock
  - pwstore-fast-2.4.4
  - text-replace-0.0.0.4
  - servant-swagger-tags-0.1.0.1
  - fsutils-0.1.2
  - oidc-client-0.6.1.0
  - raven-haskell-0.1.4.1
  - rdf4h-5.0.1
  - jose-jwt-0.9.4
  - ginger-0.10.4.0
  - lens-aeson-1.1.3

allow-newer: true
