resolver: lts-13.12

packages:
- engine-registry
- engine-shared
- engine-wizard
- engine-wizard-metamodel-migrator

extra-deps:
  - vendor/bson-generic
  - vendor/mongoDB-migration
  - fromhtml-1.0.1
  - persistent-mongoDB-2.8.0
  - pwstore-fast-2.4.4
  - pretty-terminal-0.1.0.0
  - ginger-0.9.1.0
  - HaskellNet-SSL-0.3.4.1
  - github-0.21
  - http-api-data-0.3.10
  - jwt-0.9.0
  - mime-mail-0.5.0
  - github: jtdaugherty/HaskellNet
    commit: "2c3da32"
  - text-replace-0.0.0.4
