resolver: nightly-2023-03-05

packages:
- engine-registry
- engine-shared
- engine-wizard
- engine-wizard-metamodel-migrator

extra-deps:
  - vendor/postgresql-migration
  - vendor/servant-errors
  - vendor/servant-mock
  - vendor/rdf4h
  - text-replace-0.0.0.4
  - servant-swagger-tags-0.1.0.1
  - fsutils-0.1.2
  - oidc-client-0.6.1.0
  - raven-haskell-0.1.4.1
  - ginger-0.10.4.0
  - minio-hs-1.6.0
  - servant-multipart-0.12.1
  - relude-1.1.0.0
  - servant-docs-0.12
  - servant-foreign-0.15.4

allow-newer: true
