resolver: lts-18.5

packages:
- engine-registry
- engine-shared
- engine-wizard
- engine-wizard-metamodel-migrator

extra-deps:
  - vendor/postgresql-migration
  - pwstore-fast-2.4.4
  - pretty-terminal-0.1.0.0
  - cron-0.7.0
  - ginger-0.10.0.5
  - text-replace-0.0.0.4
  - servant-errors-0.1.3.1
  - servant-mock-0.8.7
  - servant-multipart-0.11.4
  - servant-swagger-tags-0.1.0.1
  - servant-websockets-2.0.0
  - fsutils-0.1.2
  - oidc-client-0.5.0.0
  # Hack for mail
  - HaskellNet-SSL-0.3.4.1
  - github: jtdaugherty/HaskellNet
    commit: "5aa1f3b"
  - network-2.8.0.1
  - network-bsd-2.8.0.0
  - raven-haskell-0.1.4.0
  - rdf4h-5.0.1

allow-newer: true
