resolver: nightly-2024-01-10

compiler: ghc-9.10.1

packages:
- shared-common
- registry-public
- registry-server
- wizard-public
- wizard-server

extra-deps:
  - github: haskellify/postgresql-migration
    commit: v1.0.0
  - github: haskellify/rdf4h
    commit: v5.0.1
  - github: haskellify/servant-errors
    commit: v0.1.7.0
  - github: haskellify/servant-mock
    commit: v0.8.7
  - github: haskellify/cron
    commit: cef3249aae7977b607dd4638a65d6a985b2f5759
  - github: haskellify/minio-hs
    commit: 83446d193f9bba02b758d2f1bd34a642f575238c
  - github: JonathanLorimer/hs-connection
    commit: 1dc000d38963de0e4c3954b27d4fe0e5f1d9cee2
  - github: brendanhay/amazonka
    commit: f3a7fca02fdbb832cc348e991983b1465225d50c
    subdirs:
      - lib/amazonka
      - lib/amazonka-core
      - lib/services/amazonka-lambda
      - lib/services/amazonka-sso
      - lib/services/amazonka-sts
  - microlens-pro-0.2.0.2
  - base64-1.0
  - fsutils-0.1.2
  - ginger-0.10.5.2
  - hashable-1.5.0.0
  - haskell-src-meta-0.8.14
  - html-entities-1.1.4.7
  - jose-jwt-0.10.0
  - lens-5.3.3
  - oidc-client-0.6.1.0
  - raven-haskell-0.1.4.1
  - servant-swagger-1.2
  - servant-swagger-tags-0.1.0.1
  - servant-swagger-ui-0.3.5.5.0.0
  - servant-swagger-ui-core-0.3.5
  - swagger2-2.8.8
  - text-short-0.1.6
  - text-replace-0.0.0.4
  - th-compat-0.1.6
  - time-parsers-0.2

extra-lib-dirs:
  - ./lib

allow-newer: true
