resolver: lts-14.27

packages:
- engine-registry
- engine-shared
- engine-wizard
- engine-wizard-metamodel-migrator

extra-deps:
  - vendor/bson-generic
  - vendor/mongoDB-migration
  - persistent-mongoDB-2.8.0
  - pwstore-fast-2.4.4
  - pretty-terminal-0.1.0.0
  - ginger-0.9.1.0
  - text-replace-0.0.0.4
  - servant-errors-0.1.3.1
  - servant-multipart-0.11.4
  # Hack for mail
  - HaskellNet-SSL-0.3.4.1
  - github: jtdaugherty/HaskellNet
    commit: "5aa1f3b"
  - network-2.8.0.1
  - network-bsd-2.8.0.0
  - mongoDB-2.4.0.0

allow-newer: true
