resolver: nightly-2024-05-26

packages:
- shared-common
- registry-public
- registry-server
- wizard-common
- wizard-public
- wizard-server

extra-deps:
  - github: haskellify/postgresql-migration
    commit: v1.0.0
  - github: haskellify/rdf4h
    commit: v5.0.1
  - github: haskellify/servant-errors
    commit: v0.1.7.0
  - github: haskellify/servant-mock
    commit: v0.8.7
  - github: haskellify/cron
    commit: cef3249aae7977b607dd4638a65d6a985b2f5759
  - github: haskellify/minio-hs
    commit: 83446d193f9bba02b758d2f1bd34a642f575238c
  - github: JonathanLorimer/hs-connection
    commit: 1dc000d38963de0e4c3954b27d4fe0e5f1d9cee2
  - github: endgame/amazonka
    commit: 0c1813fe8e48d726a91e7dcf239ac9e6db64dff3
    subdirs:
      - lib/amazonka
      - lib/amazonka-core
      - lib/services/amazonka-lambda
      - lib/services/amazonka-sso
      - lib/services/amazonka-sts
  - text-replace-0.0.0.4
  - servant-swagger-tags-0.1.0.1
  - servant-swagger-ui-0.3.5.5.0.0
  - servant-swagger-ui-core-0.3.5
  - fsutils-0.1.2
  - oidc-client-0.6.1.0
  - raven-haskell-0.1.4.1
  - ginger-0.10.5.2
  - time-parsers-0.2

allow-newer: true
