module WizardLib.DocumentTemplate.Api.Resource.DocumentTemplate.DocumentTemplateFormatSimpleSM where

import Data.Swagger

import Shared.Common.Util.Swagger
import WizardLib.DocumentTemplate.Api.Resource.DocumentTemplate.DocumentTemplateFormatSimpleJM ()
import WizardLib.DocumentTemplate.Database.Migration.Development.DocumentTemplate.Data.DocumentTemplateFormats
import WizardLib.DocumentTemplate.Model.DocumentTemplate.DocumentTemplateFormatSimple

instance ToSchema DocumentTemplateFormatSimple where
  declareNamedSchema = toSwagger formatJsonSimple
