name: engine-registry
version: '2.12.0'
synopsis: Engine Registry
description: Engine Registry
category: Web
author: Vojtech Knaisl <vknaisl@gmail.com>
maintainer: Vojtech Knaisl <vknaisl@gmail.com>
copyright: 2019 Vojtech Knaisl <vknaisl@gmail.com>
license: Apache
license-file: LICENSE.md
homepage: https://github.com/engine/engine-platform-server
git: git@github.com:engine/engine-platform-server.git
bug-reports: https://github.com/engine/engine/issues
tested-with: GHC==8.6.*
library:
  source-dirs: src
  when:
  - condition: os(darwin)
    then:
      ghc-options: -j +RTS -A256m -n4m -RTS -j8 -O0 -dynamic -fwarn-unused-imports -fno-warn-warnings-deprecations
    else:
      ghc-options: -O2 -fwarn-unused-imports -fno-warn-warnings-deprecations
  dependencies:
  - base
  - aeson
  - bson
  - bson-generic
  - bytestring
  - case-insensitive
  - conduit
  - containers
  - data-default
  - directory
  - exceptions
  - filepath
  - engine-shared
  - ginger
  - hashable
  - HaskellNet
  - HaskellNet-SSL
  - http-types
  - lens
  - lens-aeson
  - memory
  - mime-mail
  - mime-types
  - minio-hs
  - mtl
  - monad-control
  - monad-logger
  - network
  - postgresql-simple
  - postgresql-libpq
  - postgresql-migration
  - pretty-simple
  - pretty-terminal
  - pwstore-fast
  - random
  - regex-compat
  - resource-pool
  - servant
  - servant-errors
  - servant-server
  - servant-swagger
  - servant-swagger-ui
  - swagger2
  - text
  - text-replace
  - time
  - transformers
  - unordered-containers
  - uri-encode
  - uuid
  - vector
  - wai
  - wai-extra
  - warp
  - wreq
  - yaml
  - zip-archive

executables:
  engine-registry:
    main: Main.hs
    source-dirs: app
    when:
    - condition: os(darwin)
      then:
        ghc-options: -j +RTS -A256m -n4m -RTS -j8 -O0 -dynamic -fwarn-unused-imports -fno-warn-warnings-deprecations
      else:
        ghc-options: -O2 -fwarn-unused-imports -fno-warn-warnings-deprecations
    dependencies:
    - base
    - engine-registry
tests:
  hspec:
    main: Spec.hs
    source-dirs: test
    when:
    - condition: os(darwin)
      then:
        ghc-options: -j +RTS -A256m -n4m -RTS -j8 -O0 -dynamic -fwarn-unused-imports -fno-warn-warnings-deprecations
      else:
        ghc-options: -O2 -fwarn-unused-imports -fno-warn-warnings-deprecations
    dependencies:
    - base
    - aeson
    - bson
    - bson-generic
    - bytestring
    - case-insensitive
    - containers
    - data-default
    - engine-shared
    - ginger
    - http-types
    - lens
    - mtl
    - monad-control
    - monad-logger
    - network
    - persistent
    - pretty-simple
    - pwstore-fast
    - random
    - regex-compat
    - servant
    - servant-server
    - servant-errors
    - text
    - time
    - transformers
    - unordered-containers
    - uuid
    - vector
    - wai
    - wai-extra
    - warp
    - yaml
    - engine-registry
    - hspec
    - hspec-expectations-pretty-diff
    - hspec-wai

default-extensions:
  - DataKinds
  - DeriveGeneric
  - DuplicateRecordFields
  - ExistentialQuantification
  - ExtendedDefaultRules
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - OverloadedStrings
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - TypeSynonymInstances
  - UnicodeSyntax
