name: engine-wizard
version: '3.11.0'
synopsis: Engine Wizard
description: Engine Wizard
category: Web
author: Vojtech Knaisl <vknaisl@gmail.com>
maintainer: Vojtech Knaisl <vknaisl@gmail.com>
copyright: 2019 Vojtech Knaisl <vknaisl@gmail.com>
license: Apache
license-file: LICENSE.md
homepage: https://github.com/engine/engine-platform-server
git: git@github.com:engine/engine-platform-server.git
bug-reports: https://github.com/engine/engine/issues
tested-with: GHC==8.6.*
library:
  source-dirs: src
  when:
  - condition: os(darwin)
    then:
      ghc-options: -O0 -dynamic -fwarn-unused-imports -fno-warn-warnings-deprecations
    else:
      ghc-options: -O0 -fwarn-unused-imports -fno-warn-warnings-deprecations
  dependencies:
  - base
  - aeson
  - async
  - base64
  - blaze-html
  - bytestring
  - cache
  - case-insensitive
  - clock
  - conduit
  - containers
  - cron
  - data-default
  - engine-wizard-metamodel-migrator
  - engine-registry
  - engine-shared
  - exceptions
  - ginger
  - hashable
  - http-client
  - http-client-tls
  - http-types
  - jwt
  - lens
  - lens-aeson
  - markdown
  - minio-hs
  - mtl
  - monad-control
  - monad-logger
  - network
  - oidc-client
  - postgresql-simple
  - postgresql-libpq
  - postgresql-migration
  - pretty-simple
  - pretty-terminal
  - pwstore-fast
  - random # OK
  - raven-haskell
  - raw-strings-qq
  - rdf4h
  - regex-compat
  - resource-pool
  - scientific
  - servant
  - servant-client
  - servant-client-core
  - servant-errors
  - servant-multipart
  - servant-server
  - servant-swagger
  - servant-swagger-tags
  - servant-swagger-ui
  - servant-websockets
  - swagger2
  - text
  - text-replace
  - time
  - time-manager
  - transformers
  - unix
  - unordered-containers
  - uri-encode
  - uuid
  - vector
  - wai
  - wai-extra
  - warp # OK
  - websockets
  - wreq # OK
  - yaml # OK
  - zip-archive
  - resourcet
  - wai-websockets

executables:
  engine-wizard:
    main: Main.hs
    source-dirs: app
    when:
    - condition: os(darwin)
      then:
        ghc-options: -threaded -O0 -dynamic -fwarn-unused-imports -fno-warn-warnings-deprecations
      else:
        ghc-options: -threaded -O0 -fwarn-unused-imports -fno-warn-warnings-deprecations
    dependencies:
    - base
    - engine-wizard
tests:
  hspec:
    main: Spec.hs
    source-dirs: test
    when:
    - condition: os(darwin)
      then:
        ghc-options: -threaded -O0 -dynamic -fwarn-unused-imports -fno-warn-warnings-deprecations
      else:
        ghc-options: -threaded -O0 -fwarn-unused-imports -fno-warn-warnings-deprecations
    dependencies:
    - base
    - aeson
    - async
    - bytestring
    - cache
    - case-insensitive
    - containers
    - data-default
    - engine-shared
    - ginger
    - http-client
    - http-types
    - lens
    - jwt
    - mtl
    - monad-control
    - monad-logger
    - network
    - pretty-simple
    - pwstore-fast
    - random
    - regex-compat
    - servant
    - servant-server
    - servant-errors
    - text
    - time
    - transformers
    - unordered-containers
    - uuid
    - vector
    - wai
    - wai-extra
    - warp
    - websockets
    - yaml
    - engine-wizard
    - hspec
    - hspec-expectations-pretty-diff
    - hspec-wai

default-extensions:
  - DataKinds
  - DeriveGeneric
  - DuplicateRecordFields
  - ExistentialQuantification
  - ExtendedDefaultRules
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - OverloadedStrings
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - TypeSynonymInstances
  - UnicodeSyntax
