name: engine-wizard
version: '2.3.0'
synopsis: Engine Wizard
description: Engine Wizard
category: Web
author: Vojtech Knaisl <vknaisl@gmail.com>
maintainer: Vojtech Knaisl <vknaisl@gmail.com>
copyright: 2019 Vojtech Knaisl <vknaisl@gmail.com>
license: Apache
license-file: LICENSE.md
homepage: https://github.com/engine/engine-platform-server
git: git@github.com:engine/engine-platform-server.git
bug-reports: https://github.com/engine/engine/issues
tested-with: GHC==8.6.*
library:
  source-dirs: src
  when:
  - condition: os(darwin)
    then:
      ghc-options: -j +RTS -A256m -n4m -RTS -j8 -O0 -dynamic -fwarn-unused-imports -fno-warn-warnings-deprecations
    else:
      ghc-options: -j +RTS -A256m -n4m -RTS -j8 -O2 -fwarn-unused-imports -fno-warn-warnings-deprecations
  dependencies:
  - base
  - aeson
  - amqp
  - async
  - blaze-html
  - bson
  - bson-generic
  - bytestring
  - case-insensitive
  - conduit
  - containers
  - data-default
  - directory
  - engine-wizard-metamodel-migrator
  - engine-registry
  - engine-shared
  - exceptions
  - filepath
  - ginger
  - hashable
  - HaskellNet
  - HaskellNet-SSL
  - http-client
  - http-client-tls
  - http-types
  - jwt
  - lens
  - lens-aeson
  - markdown
  - mime-mail
  - mime-types
  - mtl
  - monad-control
  - monad-logger
  - mongoDB
  - mongoDB-migration
  - network # OK
  - oidc-client
  - persistent
  - persistent-mongoDB
  - pretty-simple
  - pretty-terminal
  - pwstore-fast
  - random # OK
  - regex-compat
  - retry
  - scientific
  - servant
  - servant-client
  - servant-client-core
  - servant-errors
  - servant-multipart
  - servant-server
  - servant-swagger
  - servant-swagger-ui
  - swagger2
  - text
  - text-replace
  - time
  - transformers
  - unordered-containers
  - uri-encode
  - uuid
  - vector
  - wai
  - wai-extra
  - warp # OK
  - wreq # OK
  - yaml # OK

executables:
  engine-wizard:
    main: Main.hs
    source-dirs: app
    when:
    - condition: os(darwin)
      then:
        ghc-options: -j +RTS -A256m -n4m -RTS -j8 -O0 -dynamic -fwarn-unused-imports -fno-warn-warnings-deprecations
      else:
        ghc-options: -j +RTS -A256m -n4m -RTS -j8 -O2 -fwarn-unused-imports -fno-warn-warnings-deprecations
    dependencies:
    - base
    - engine-wizard
tests:
  hspec:
    main: Spec.hs
    source-dirs: test
    when:
    - condition: os(darwin)
      then:
        ghc-options: -j +RTS -A256m -n4m -RTS -j8 -O0 -dynamic -fwarn-unused-imports -fno-warn-warnings-deprecations
      else:
        ghc-options: -j +RTS -A256m -n4m -RTS -j8 -O2 -fwarn-unused-imports -fno-warn-warnings-deprecations
    dependencies:
    - base
    - aeson
    - amqp
    - async
    - bson
    - bson-generic
    - bytestring
    - case-insensitive
    - containers
    - data-default
    - engine-shared
    - ginger
    - http-client
    - http-types
    - lens
    - jwt
    - mtl
    - monad-control
    - monad-logger
    - mongoDB
    - network
    - persistent
    - persistent-mongoDB
    - pretty-simple
    - pwstore-fast
    - random
    - regex-compat
    - servant
    - servant-server
    - servant-errors
    - text
    - time
    - transformers
    - unordered-containers
    - uuid
    - vector
    - wai
    - wai-extra
    - warp
    - yaml
    - engine-wizard
    - hspec
    - hspec-expectations-pretty-diff
    - hspec-wai
    - hspec-wai-json

default-extensions:
  - TemplateHaskell
  - QuasiQuotes
  - OverloadedStrings
  - DeriveGeneric
  - FlexibleContexts
  - RecordWildCards
  - ScopedTypeVariables
  - ExtendedDefaultRules
  - FlexibleInstances
  - MultiParamTypeClasses
  - GeneralizedNewtypeDeriving
  - TypeFamilies
  - UnicodeSyntax
  - ExistentialQuantification
  - FunctionalDependencies
  - TypeSynonymInstances
  - RankNTypes
  - DataKinds
  - TypeOperators
  - TypeApplications