module Shared.Common.Model.User.RolePermission where

_DEV_USE_ROLE_PERMISSION :: String
_DEV_USE_ROLE_PERMISSION = "DevUseRolePermission"

_LOCALES_MANAGE_ROLE_PERMISSION :: String
_LOCALES_MANAGE_ROLE_PERMISSION = "LocalesManageRolePermission"

_SETTINGS_MANAGE_ROLE_PERMISSION :: String
_SETTINGS_MANAGE_ROLE_PERMISSION = "SettingsManageRolePermission"

_TENANTS_MANAGE_ROLE_PERMISSION :: String
_TENANTS_MANAGE_ROLE_PERMISSION = "TenantsManageRolePermission"

_USERS_MANAGE_ROLE_PERMISSION :: String
_USERS_MANAGE_ROLE_PERMISSION = "UsersManageRolePermission"
