module Wizard.Constant.Acl where

_APP_PERM = "APP_PERM"

_DEV_PERM = "DEV_PERM"

_UM_PERM = "UM_PERM"

_KM_PERM = "KM_PERM"

_KM_UPGRADE_PERM = "KM_UPGRADE_PERM"

_KM_PUBLISH_PERM = "KM_PUBLISH_PERM"

_PM_READ_PERM = "PM_READ_PERM"

_PM_WRITE_PERM = "PM_WRITE_PERM"

_QTN_PERM = "QTN_PERM"

_QTN_TML_PERM = "QTN_TML_PERM"

_QTN_IMPORTER_PERM = "QTN_IMPORTER_PERM"

_DMP_PERM = "DMP_PERM"

_CFG_PERM = "CFG_PERM"

_SUBM_PERM = "SUBM_PERM"

_TML_PERM = "TML_PERM"

_DOC_PERM = "DOC_PERM"
