module WizardLib.Public.Model.User.RolePermission (
  module Shared.Common.Model.User.RolePermission,
  _DOCUMENT_TEMPLATE_EDITORS_USE_ROLE_PERMISSION,
  _DOCUMENT_TEMPLATES_MANAGE_ROLE_PERMISSION,
  _KNOWLEDGE_MODEL_EDITORS_USE_ROLE_PERMISSION,
  _KNOWLEDGE_MODELS_MANAGE_ROLE_PERMISSION,
  _PROJECT_TEMPLATES_MANAGE_ROLE_PERMISSION,
  _PROJECTS_COMMENT_ROLE_PERMISSION,
  _PROJECTS_EDIT_ROLE_PERMISSION,
  _PROJECTS_MANAGE_ROLE_PERMISSION,
  _PROJECTS_VIEW_ROLE_PERMISSION,
  allRolePermissions,
  assignableRolePermissions,
) where

import Shared.Common.Model.User.RolePermission

_DOCUMENT_TEMPLATE_EDITORS_USE_ROLE_PERMISSION :: String
_DOCUMENT_TEMPLATE_EDITORS_USE_ROLE_PERMISSION = "DocumentTemplateEditorsUseRolePermission"

_DOCUMENT_TEMPLATES_MANAGE_ROLE_PERMISSION :: String
_DOCUMENT_TEMPLATES_MANAGE_ROLE_PERMISSION = "DocumentTemplatesManageRolePermission"

_KNOWLEDGE_MODEL_EDITORS_USE_ROLE_PERMISSION :: String
_KNOWLEDGE_MODEL_EDITORS_USE_ROLE_PERMISSION = "KnowledgeModelEditorsUseRolePermission"

_KNOWLEDGE_MODELS_MANAGE_ROLE_PERMISSION :: String
_KNOWLEDGE_MODELS_MANAGE_ROLE_PERMISSION = "KnowledgeModelsManageRolePermission"

_PROJECT_TEMPLATES_MANAGE_ROLE_PERMISSION :: String
_PROJECT_TEMPLATES_MANAGE_ROLE_PERMISSION = "ProjectTemplatesManageRolePermission"

_PROJECTS_COMMENT_ROLE_PERMISSION :: String
_PROJECTS_COMMENT_ROLE_PERMISSION = "ProjectsCommentRolePermission"

_PROJECTS_EDIT_ROLE_PERMISSION :: String
_PROJECTS_EDIT_ROLE_PERMISSION = "ProjectsEditRolePermission"

_PROJECTS_MANAGE_ROLE_PERMISSION :: String
_PROJECTS_MANAGE_ROLE_PERMISSION = "ProjectsManageRolePermission"

_PROJECTS_VIEW_ROLE_PERMISSION :: String
_PROJECTS_VIEW_ROLE_PERMISSION = "ProjectsViewRolePermission"

allRolePermissions :: [String]
allRolePermissions =
  [ -- Shared
    _LOCALES_MANAGE_ROLE_PERMISSION
  , _SETTINGS_MANAGE_ROLE_PERMISSION
  , _USERS_MANAGE_ROLE_PERMISSION
  , -- Wizard
    _DOCUMENT_TEMPLATE_EDITORS_USE_ROLE_PERMISSION
  , _DOCUMENT_TEMPLATES_MANAGE_ROLE_PERMISSION
  , _KNOWLEDGE_MODEL_EDITORS_USE_ROLE_PERMISSION
  , _KNOWLEDGE_MODELS_MANAGE_ROLE_PERMISSION
  , _PROJECT_TEMPLATES_MANAGE_ROLE_PERMISSION
  , _PROJECTS_COMMENT_ROLE_PERMISSION
  , _PROJECTS_EDIT_ROLE_PERMISSION
  , _PROJECTS_MANAGE_ROLE_PERMISSION
  , _PROJECTS_VIEW_ROLE_PERMISSION
  ]

assignableRolePermissions :: [String]
assignableRolePermissions = allRolePermissions
