name: registry-public
version: '4.15.0'
synopsis: Registry Public
description: Registry Public
category: Web
author: Vojtech Knaisl <vknaisl@gmail.com>
maintainer: Vojtech Knaisl <vknaisl@gmail.com>
copyright: 2023 Vojtech Knaisl <vknaisl@gmail.com>
license: Apache
license-file: LICENSE.md
homepage: https://github.com/ds-wizard/engine-backend
git: git@github.com:engine/ds-wizard/engine-backend.git
bug-reports: https://github.com/ds-wizard/ds-wizard/issues
tested-with: GHC==9.4.4
library:
  source-dirs: src
  when:
  - condition: os(darwin)
    then:
      ghc-options: -O0 -fwarn-unused-imports -fno-warn-warnings-deprecations -fno-warn-ambiguous-fields -Wno-x-partial
    else:
      ghc-options: -O0 -fwarn-unused-imports -fno-warn-warnings-deprecations -fno-warn-ambiguous-fields -Wno-x-partial
  dependencies:
  - shared-common
  - wizard-common
  - base
  - aeson
  - servant-server
  - swagger2
  - time
  - uuid

default-extensions:
  - DataKinds
  - DeriveGeneric
  - DisambiguateRecordFields
  - DuplicateRecordFields
  - ExistentialQuantification
  - ExtendedDefaultRules
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - OverloadedStrings
  - OverloadedRecordDot
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - TypeSynonymInstances
  - UnicodeSyntax
