module Wizard.Constant.Acl (
  module Shared.Common.Constant.Acl,
  _UM_PERM,
  _KM_PERM,
  _KM_UPGRADE_PERM,
  _KM_PUBLISH_PERM,
  _PM_READ_PERM,
  _PM_WRITE_PERM,
  _QTN_PERM,
  _QTN_FILE_PERM,
  _QTN_TML_PERM,
  _QTN_ACTION_PERM,
  _QTN_IMPORTER_PERM,
  _SUBM_PERM,
  _DOC_TML_READ_PERM,
  _DOC_TML_WRITE_PERM,
  _DOC_PERM,
  _LOC_PERM,
) where

import Shared.Common.Constant.Acl

_UM_PERM = "UM_PERM"

_KM_PERM = "KM_PERM"

_KM_UPGRADE_PERM = "KM_UPGRADE_PERM"

_KM_PUBLISH_PERM = "KM_PUBLISH_PERM"

_PM_READ_PERM = "PM_READ_PERM"

_PM_WRITE_PERM = "PM_WRITE_PERM"

_QTN_PERM = "QTN_PERM"

_QTN_FILE_PERM = "QTN_FILE_PERM"

_QTN_TML_PERM = "QTN_TML_PERM"

_QTN_ACTION_PERM = "QTN_ACTION_PERM"

_QTN_IMPORTER_PERM = "QTN_IMPORTER_PERM"

_SUBM_PERM = "SUBM_PERM"

_DOC_TML_READ_PERM = "DOC_TML_READ_PERM"

_DOC_TML_WRITE_PERM = "DOC_TML_WRITE_PERM"

_DOC_PERM = "DOC_PERM"

_LOC_PERM = "LOC_PERM"
