module Wizard.Constant.Acl (
  module Shared.Common.Constant.Acl,
  _UM_PERM,
  _KM_PERM,
  _KM_UPGRADE_PERM,
  _KM_PUBLISH_PERM,
  _PM_READ_PERM,
  _PM_WRITE_PERM,
  _PRJ_PERM,
  _PRJ_FILE_PERM,
  _PRJ_TML_PERM,
  _PRJ_ACTION_PERM,
  _PRJ_IMPORTER_PERM,
  _SUBM_PERM,
  _DOC_TML_READ_PERM,
  _DOC_TML_WRITE_PERM,
  _DOC_PERM,
  _LOC_PERM,
) where

import Shared.Common.Constant.Acl

_UM_PERM = "UM_PERM"

_KM_PERM = "KM_PERM"

_KM_UPGRADE_PERM = "KM_UPGRADE_PERM"

_KM_PUBLISH_PERM = "KM_PUBLISH_PERM"

_PM_READ_PERM = "PM_READ_PERM"

_PM_WRITE_PERM = "PM_WRITE_PERM"

_PRJ_PERM = "PRJ_PERM"

_PRJ_FILE_PERM = "PRJ_FILE_PERM"

_PRJ_TML_PERM = "PRJ_TML_PERM"

_PRJ_ACTION_PERM = "PRJ_ACTION_PERM"

_PRJ_IMPORTER_PERM = "PRJ_IMPORTER_PERM"

_SUBM_PERM = "SUBM_PERM"

_DOC_TML_READ_PERM = "DOC_TML_READ_PERM"

_DOC_TML_WRITE_PERM = "DOC_TML_WRITE_PERM"

_DOC_PERM = "DOC_PERM"

_LOC_PERM = "LOC_PERM"
