name: engine-shared
version: '2.1.0'
synopsis: Engine Shared
description: Engine Shared
category: Web
author: Vojtech Knaisl <vknaisl@gmail.com>
maintainer: Vojtech Knaisl <vknaisl@gmail.com>
copyright: 2019 Vojtech Knaisl <vknaisl@gmail.com>
license: Apache
license-file: LICENSE.md
homepage: https://github.com/engine/engine-platform-server
git: git@github.com:engine/engine-platform-server.git
bug-reports: https://github.com/engine/engine/issues
tested-with: GHC==8.6.*
library:
  source-dirs: src
  other-modules:
  - LensesConfig
  when:
  - condition: os(darwin)
    then:
      ghc-options: -j4 +RTS -A256m -n4m -qg -RTS -O0 -dynamic -fwarn-unused-imports -fno-warn-warnings-deprecations
    else:
      ghc-options: -j4 +RTS -A256m -n4m -qg -RTS -O2 -fwarn-unused-imports -fno-warn-warnings-deprecations
  dependencies:
  - base
  - aeson
  - bytestring
  - case-insensitive
  - containers
  - directory
  - http-types
  - lens
  - monad-logger
  - random
  - servant-server
  - time
  - text
  - text-replace
  - unordered-containers
  - uuid
  - wai
  default-extensions:
    - TemplateHaskell
    - OverloadedStrings
    - DeriveGeneric
    - FlexibleContexts
    - RecordWildCards
    - ScopedTypeVariables
    - ExtendedDefaultRules
    - FlexibleInstances
    - MultiParamTypeClasses
    - GeneralizedNewtypeDeriving
    - TypeFamilies
    - UnicodeSyntax
    - ExistentialQuantification
    - FunctionalDependencies
    - TypeSynonymInstances
    - RankNTypes
tests:
  hspec:
    main: Spec.hs
    source-dirs: test
    when:
    - condition: os(darwin)
      then:
        ghc-options: -j +RTS -A256m -n4m -RTS -j8 -O0 -dynamic -fwarn-unused-imports -fno-warn-warnings-deprecations
      else:
        ghc-options: -j +RTS -A256m -n4m -RTS -j8 -O2 -fwarn-unused-imports -fno-warn-warnings-deprecations
    dependencies:
    - base
    - aeson
    - containers
    - lens
    - random
    - text
    - text-replace
    - uuid
    - engine-shared
    - hspec
    - hspec-expectations-pretty-diff
    - hspec-wai
    - hspec-wai-json
    default-extensions:
      - TemplateHaskell
      - QuasiQuotes
      - OverloadedStrings
      - MultiParamTypeClasses
      - FlexibleContexts
      - GeneralizedNewtypeDeriving
      - TypeFamilies
      - DeriveGeneric
      - ExtendedDefaultRules
      - RecordWildCards
      - UnicodeSyntax
      - ExistentialQuantification
      - FunctionalDependencies
      - TypeSynonymInstances
      - FlexibleInstances
