module Wizard.Database.BSON.Config.AppConfig where

import Data.Bson.Generic

import Shared.Database.BSON.Common ()
import Wizard.Database.BSON.Config.SimpleFeature ()
import Wizard.Model.Config.AppConfig

instance ToBSON AppConfig

instance FromBSON AppConfig

instance ToBSON AppConfigOrganization

instance FromBSON AppConfigOrganization

instance ToBSON AppConfigAuth

instance FromBSON AppConfigAuth

instance ToBSON AppConfigAuthInternal

instance FromBSON AppConfigAuthInternal

instance ToBSON AppConfigAuthExternal

instance FromBSON AppConfigAuthExternal

instance ToBSON AppConfigAuthExternalService

instance FromBSON AppConfigAuthExternalService

instance ToBSON AppConfigAuthExternalServiceParameter

instance FromBSON AppConfigAuthExternalServiceParameter

instance ToBSON AppConfigAuthExternalServiceStyle

instance FromBSON AppConfigAuthExternalServiceStyle

instance ToBSON AppConfigPrivacyAndSupport

instance FromBSON AppConfigPrivacyAndSupport

instance ToBSON AppConfigDashboard

instance FromBSON AppConfigDashboard

instance ToBSON AppConfigDashboardWidgets

instance FromBSON AppConfigDashboardWidgets

instance ToBSON AppConfigLookAndFeel

instance FromBSON AppConfigLookAndFeel

instance ToBSON AppConfigLookAndFeelCustomMenuLink

instance FromBSON AppConfigLookAndFeelCustomMenuLink

instance ToBSON AppConfigRegistry

instance FromBSON AppConfigRegistry

instance ToBSON AppConfigQuestionnaire

instance FromBSON AppConfigQuestionnaire

instance ToBSON AppConfigQuestionnaireFeedback

instance FromBSON AppConfigQuestionnaireFeedback

instance ToBSON AppConfigTemplate

instance FromBSON AppConfigTemplate

instance ToBSON AppConfigSubmission

instance FromBSON AppConfigSubmission

instance ToBSON AppConfigSubmissionService

instance FromBSON AppConfigSubmissionService

instance ToBSON AppConfigSubmissionServiceSupportedFormat

instance FromBSON AppConfigSubmissionServiceSupportedFormat

instance ToBSON AppConfigSubmissionServiceRequest

instance FromBSON AppConfigSubmissionServiceRequest

instance ToBSON AppConfigSubmissionServiceRequestMultipart

instance FromBSON AppConfigSubmissionServiceRequestMultipart
