name:                wizard-metamodel-migrator
version:             "3.23.0"
license:             Apache-2.0
author:              "Marek Suchánek"
maintainer:          "suchama4@fit.cvut.cz"
copyright:           "2022 Marek Suchánek"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Library for migrating Engine KMs when the Engine Metamodel changes

dependencies:
- base >= 4.7 && < 5
- aeson
- containers
- text
- time
- vector
- unordered-containers
- uuid

library:
  source-dirs: src
  when:
  - condition: os(darwin)
    then:
      ghc-options: -O0 -fwarn-unused-imports -fno-warn-warnings-deprecations
    else:
      ghc-options: -O2 -fwarn-unused-imports -fno-warn-warnings-deprecations

executables:
  event-migrator:
    main:                Main.hs
    source-dirs:         app
    when:
    - condition: os(darwin)
      then:
        ghc-options: -threaded -O0 -fwarn-unused-imports -fno-warn-warnings-deprecations
      else:
        ghc-options: -threaded -O2 -fwarn-unused-imports -fno-warn-warnings-deprecations
    dependencies:
    - wizard-metamodel-migrator
    - bytestring

tests:
  json-playground-test:
    main:                Spec.hs
    source-dirs:         test
    when:
    - condition: os(darwin)
      then:
        ghc-options: -threaded -O0 -fwarn-unused-imports -fno-warn-warnings-deprecations
      else:
        ghc-options: -threaded -O2 -fwarn-unused-imports -fno-warn-warnings-deprecations
    dependencies:
    - wizard-metamodel-migrator
    - aeson-qq
    - hspec
    - hspec-expectations-json
    default-extensions:
    - QuasiQuotes

default-extensions:
- OverloadedStrings
